@startuml

class Dancer {
   - firstname
   - lastname
   - address
   - age
}

class DanceTeacher{
}

class Group {
   - name
   - ageLimit
   - dancerLimit
}

class DanceClass{
   - time
}

class Room{
    - number
    - personLimit
}

Dancer <|-- DanceTeacher
Group "1" -up- "*" Dancer : has >
Group "1" -down- "1..*" DanceClass : assigned to >
DanceClass "1" -down- "1" Room : is in >
@enduml